version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
      - image: circleci/postgres:11.3


   steps:
      - checkout
      
      # update npm
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'

      # download and cache dependencies
      - restore_cache:
          key:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package.json" }}

      # seed database
      - run: npm run seed
      
      # run tests
      -rum: npm run test
      
